function material = FYS_vonMises

material.name = 'FYS_vonMises';

%% Scalar Parameters
material.E = 210; % Young's modulus (Neto et al.) [GPa = kN/mm^2]
material.nu = 0.3; % Poisson's ratio (Neto et al.) [-]
material.lambda = material.E*material.nu / ((1+material.nu)*(1-2*material.nu));
material.mu = material.E / (2*(1+material.nu)); % shear modulus
material.K = material.E / (3*(1-2*material.nu)); % bulk modulus
material.sigma_0 = 0.24; % yield stress (Neto et al.) [GPa = kN/mm^2]

%% Elastic Properties (3D)
material.C = [ ...
    material.lambda+2*material.mu, material.lambda, material.lambda, 0, 0, 0;...
    material.lambda, material.lambda+2*material.mu, material.lambda, 0, 0, 0;...
    material.lambda, material.lambda, material.lambda+2*material.mu, 0, 0, 0;...
    0, 0, 0, material.mu, 0, 0;...
    0, 0, 0, 0, material.mu, 0;...
    0, 0, 0, 0, 0, material.mu;...
    ];

material.S = [ ...
    1/material.E, -material.nu/material.E, -material.nu/material.E, 0, 0, 0;...
    -material.nu/material.E, 1/material.E, -material.nu/material.E, 0, 0, 0;...
    -material.nu/material.E, -material.nu/material.E, 1/material.E, 0, 0, 0;...
    0, 0, 0, 1/material.mu, 0, 0;...
    0, 0, 0, 0, 1/material.mu, 0;...
    0, 0, 0, 0, 0, 1/material.mu;...
    ];

%% Elastic Properties (Plane Strain)
material.CPlaneStrain = [ ...
    material.lambda+2*material.mu, material.lambda, 0;...
    material.lambda, material.lambda+2*material.mu, 0;...
    0, 0, material.mu;...
    ];
% material.CPlaneStrain = E/((1+nu)*(1-2*nu)) * [ ...
%     1-nu, nu, 0;...
%     nu, 1-nu, 0;...
%     0, 0, 1/2-nu;...
%     ];

material.SPlaneStrain = inv(material.CPlaneStrain);

%% Elastic Properties (Plane Stress)
material.CPlaneStress = material.E/(1-material.nu^2) * [ ...
    1, material.nu, 0;...
    material.nu, 1, 0;...
    0, 0, 1/2*(1-material.nu);...
    ];

material.SPlaneStress = [ ...
    1/material.E, -material.nu/material.E, 0;...
    -material.nu/material.E, 1/material.E, 0;...
    0, 0, 1/material.mu;...
    ];
% material.SPlaneStress = inv(material.CPlaneStress);

%% Plastic Properties
material.fourier_coeff = [...
    material.sigma_0; ...
    0; ...
    ];
material.theta = material.fourier_coeff(1,1:3:end);
