function CC = get_CCFD_PlaneStress_Tresca( ...
    n_NR_local, ...
    tol_NR_local, ...
    E, ...
    nu, ...
    mu, ...
    CPlaneStress, ...
    SPlaneStress, ...
    sigma_0, ...
    epsilonV, ...
    epsilonVp_prev, ...
    FD ...
    )
% get_CCFD_PlaneStress_Tresca computes the consistent tangent modulus for the
% Tresca model using finite differences

CC = zeros(3,3);
for i = 1:3
    depsilonV = zeros(size(epsilonV));
    depsilonV(i) = FD;
    
    epsilonV_plus = epsilonV + 0.5*depsilonV;
    sigmaV_plus = local_problem_PlaneStress_Tresca( ...
        n_NR_local, ...
        tol_NR_local, ...
        E, ...
        nu, ...
        mu, ...
        CPlaneStress, ...
        SPlaneStress, ...
        sigma_0, ...
        epsilonV_plus, ...
        epsilonVp_prev ...
        );
    epsilonV_minus = epsilonV - 0.5*depsilonV;
    sigmaV_minus = local_problem_PlaneStress_Tresca( ...
        n_NR_local, ...
        tol_NR_local, ...
        E, ...
        nu, ...
        mu, ...
        CPlaneStress, ...
        SPlaneStress, ...
        sigma_0, ...
        epsilonV_minus, ...
        epsilonVp_prev ...
        );
    
    CC(:,i) = (sigmaV_plus - sigmaV_minus)/FD;
end

end