function CC = get_CCFD_PlaneStress( ...
    n_NR_local, ...
    tol_NR_local, ...
    CPlaneStress, ...
    SPlaneStress, ...
    theta, ...
    epsilonV, ...
    epsilonVp_prev, ...
    FD ...
    )
% get_CCFD_PlaneStress computes the consistent tangent modulus
% using finite differences

CC = zeros(3,3);
for i = 1:3
    depsilonV = zeros(size(epsilonV));
    depsilonV(i) = FD;
    
    epsilonV_plus = epsilonV + 0.5*depsilonV;
    sigmaV_plus = local_problem_PlaneStress( ...
        n_NR_local, ...
        tol_NR_local, ...
        CPlaneStress, ...
        SPlaneStress, ...
        theta, ...
        epsilonV_plus, ...
        epsilonVp_prev ...
        );
    epsilonV_minus = epsilonV - 0.5*depsilonV;
    sigmaV_minus = local_problem_PlaneStress( ...
        n_NR_local, ...
        tol_NR_local, ...
        CPlaneStress, ...
        SPlaneStress, ...
        theta, ...
        epsilonV_minus, ...
        epsilonVp_prev ...
        );
    
    CC(:,i) = (sigmaV_plus - sigmaV_minus)/FD;
end

end