function epsilonV = epsilon2V(epsilon)
% epsilon2V transforms the infinitesimal strain from matrix to vector
% (Voigt) representation.

if length(epsilon) == 3
    epsilonV = [...
        epsilon(1,1);...
        epsilon(2,2);...
        epsilon(3,3);...
        2*epsilon(2,3);...
        2*epsilon(1,3);...
        2*epsilon(1,2);...
        ];
elseif length(epsilon) == 2
    epsilonV = [...
        epsilon(1,1);...
        epsilon(2,2);...
        2*epsilon(1,2);...
        ];
else
    error('Input must have either 3x3 components in 3D or 2x2 components in 2D.')
end

end