function sigmaV = sigma2V(sigma)
% sigma2V transforms the Cauchy stress from matrix to vector (Voigt)
% representation.

if length(sigma) == 3
    sigmaV = [...
        sigma(1,1);...
        sigma(2,2);...
        sigma(3,3);...
        sigma(2,3);...
        sigma(1,3);...
        sigma(1,2);...
        ];
elseif length(sigma) == 2
    sigmaV = [...
        sigma(1,1);...
        sigma(2,2);...
        sigma(1,2);...
        ];
else
    error('Input must have either 3x3 components in 3D or 2x2 components in 2D.')
end

end