function sigmaV = sigmaVPlaneStress2sigmaV(sigmaVPlaneStress)
sigmaV = [...
    sigmaVPlaneStress(1);...
    sigmaVPlaneStress(2);...
    0;...
    0;...
    0;...
    sigmaVPlaneStress(3);...
    ];
end