function epsilon = V2epsilon(epsilonV)
% V2epsilon transforms the infinitesimal strain from vector (Voigt) to
% matrix representation.

if length(epsilonV) == 6
    epsilon = [...
        epsilonV(1), 1/2*epsilonV(6), 1/2*epsilonV(5);...
        1/2*epsilonV(6), epsilonV(2), 1/2*epsilonV(4);...
        1/2*epsilonV(5), 1/2*epsilonV(4), epsilonV(3);...
        ];
elseif length(epsilonV) == 3
    epsilon = [...
        epsilonV(1), 1/2*epsilonV(3);...
        1/2*epsilonV(3), epsilonV(2);...
        ];
elseif length(epsilonV) == 4
    epsilon = [...
        epsilonV(1), 1/2*epsilonV(3), 0;...
        1/2*epsilonV(3), epsilonV(2), 0;...
        0, 0, epsilonV(4);...
        ];
else
    error('Input must have either 6 components in 3D or 3 components in 2D.')
end

end