function sigma = V2sigma(sigmaV)
% V2sigma transforms the Cauchy stress from vector (Voigt) to matrix
% representation.

if length(sigmaV) == 6
    sigma = [...
        sigmaV(1), sigmaV(6), sigmaV(5);...
        sigmaV(6), sigmaV(2), sigmaV(4);...
        sigmaV(5), sigmaV(4), sigmaV(3);...
        ];
elseif length(sigmaV) == 3
    sigma = [...
        sigmaV(1), sigmaV(3);...
        sigmaV(3), sigmaV(2);...
        ];
else
    error('Input must have either 6 components in 3D or 3 components in 2D.')
end

end