site_name: EUCLID / Plasticity
site_url: https://pyeuclid.github.io/
nav:
    - Home: index.md
    - Publication: publication.md
    - Code/Data: code_data.md
    - Example: example_plasticity_w_hardening.md
    - Code:
        - Notation: notation.md
        - def_objective_vec_HardMixVAF: code/def_objective_vec_HardMixVAF.md
        - FEA_plate_elliptic_holes: code/FEA_plate_elliptic_holes.md
        - get_CCFD_PlaneStressHardMixVAF: code/get_CCFD_PlaneStressHardMixVAF.md
        - get_df_PlaneStressHardMixVAF: code/get_df_PlaneStressHardMixVAF.md
        - get_df_PlaneStressHardMixVAF_FD: code/get_df_PlaneStressHardMixVAF_FD.md
        - get_f_PlaneStressHardMixVAF: code/get_f_PlaneStressHardMixVAF.md
        - global_problem_call: code/global_problem_call.md
        - global_problem_PlaneStressHardMixVAF: code/global_problem_PlaneStressHardMixVAF.md
        - local_problem_PlaneStressHardMixVAF: code/local_problem_PlaneStressHardMixVAF.md
        - local_problem_PlaneStressHardMixVAF_notan: code/local_problem_PlaneStressHardMixVAF_notan.md
        - mesh_info: code/mesh_info.md
        - objective_vec_HardMixVAF: code/objective_vec_HardMixVAF.md
        - opt_HardMix: code/opt_HardMix.md
        - opt_input_HardMix: code/opt_input_HardMix.md
        - selection_best_random_HardMixVAF: code/selection_best_random_HardMixVAF.md
        - selection_best_random_HardMixVAF: code/selection_best_random_HardMixVAF.md
        - selection_HardMix: code/selection_HardMix.md
        - selection_threshold: code/selection_threshold.md
theme: readthedocs
